name: GitHub Activity Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important! Prevents using GITHUB_TOKEN

      - name: Configure Git
        run: |
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "cfelix2@lsu.edu"

      - name: Make changes
        run: |
          echo "$(date)" >> activity_log.txt
          git add activity_log.txt
          git commit -m "GitHub Activity Update: $(date)"

      - name: Push changes using PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/YourGitHubUsername/YourRepo.git
          git push origin main
