name: GitHub Activity

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 12 * * *"  # Runs every day at noon UTC

jobs:
  generate_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Past Contributions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create past commits for the last 700 days
          for i in {1..700}; do
            DATE=$(date -d "$i days ago" +%Y-%m-%dT%H:%M:%S)
            echo "GitHub Activity Update: $DATE" > activity_log.txt
            git add activity_log.txt
            GIT_AUTHOR_DATE="$DATE" GIT_COMMITTER_DATE="$DATE" git commit -m "GitHub Activity Update: $DATE"
          done

          git push
